---
- name: Instalar Apache
  apt:
    update_cache: yes
    pkg:
      apache2

- name: Crear directorio para el sitio
  ansible.builtin.file:
    path: /var/www/{{ item.name }}
    state: directory
    mode: '0755' 
  loop: "{{ apache_virtualhosts }}"
  notify: restart apache2

- name: Create vhost
  ansible.builtin.template:
  #por defecto lo busca en templates...
    src: Apache/vhosts.j2
    dest: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
  loop: "{{ apache_virtualhosts }}"

- name: Copy index test page
  ansible.builtin.template:
    src: Apache/index.html.j2
    dest: "/var/www/{{ item.name }}/index.html"
  loop: "{{ apache_virtualhosts }}"

- name: Enable service httpd 
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

