- name: Create a directory
  ansible.windows.win_file:
    path: C:\inetpub\wwwroot\sitio.logs
    state: directory

- name: Create a new hello application pool
  win_iis_webapppool:
    name: hello
    state: started

#- name: Borro un application pool
#  win_iis_webapppool:
#    name: hello
#    state: absent

- name: Hello IIS site
  community.windows.win_iis_website:
    name: hello
    state: started
    port: 8080
    ip: '*'
    hostname: 'vm-curso-win'
    application_pool: hello
    physical_path: C:\inetpub\wwwroot\sitio
    parameters: logfile.directory:C:\inetpub\wwwroot\sitio.logs
  register: website

#- name: Add api hello on IIS.
#  win_iis_webapplication:
#   name: api
#   site: vm-curo-win
#   state: present
#   physical_path: C:\inetpub\wwwroot\sitio

# Remove Default Web Site and the standard port 80 binding
#- name: Remove hello Web Site
#  community.windows.win_iis_website:
#    name: hello
#    state: absent
#  register: website

# Remove Default Web Site and the standard port 80 binding
#- name: Remove Default Web Site
#  community.windows.win_iis_website:
#    name: "Default Web Site"
#    state: absent

# Create a WebSite with custom Logging configuration (Logs Location, Format and Rolling Over).

#- name: Creating WebSite with Custom Log location, Format 3WC and rolling over every hour.
#  community.windows.win_iis_website:
#    name: MyCustom_Web_Shop_Site
#    state: started
#    port: 80
#    ip: '*'
#    hostname: '*'
#    physical_path: D:\wwwroot\websites\my-shop-site
#    parameters: logfile.directory:D:\IIS-LOGS\websites\my-shop-site|logfile.period:Hourly|logFile.logFormat:W3C
#    application_pool: my-shop-site  

########### full stack ##############
#- name: Create a new application pool - ansiblepool in 'Started' state
#  win_iis_webapppool:
#   name: ansiblepool
#   state: started

#- name: IIS site
#  win_iis_website:
#   name: iis_via_ansible.org
#   state: started
#   port: 80
#   ip: 127.0.0.1
#   hostname: localhost
#   application_pool: ansiblepool
#   physical_path: C:\sites\
#   parameters: logfile.directory:C:\sites\logs
#  register: website

#- name: Add api webapplication on IIS.
#  win_iis_webapplication:
#   name: api
#   site: iis_via_ansible.org
#   state: present
#   physical_path: C:\sites\api

- debug: msg={{ website }}
