---
- hosts: all
  become: yes
  tasks:
    - name: Cambiar IP de la red...
      lineinfile:
        dest: /etc/network/interfaces
        #regexp: '^127\.0\.1\.1[ \t]+debian10temp'
        regexp: 'address 10\.45\.0\.200\/24'
        line: '        address {{ template_ip }}/24'
        state: present

    - name: Cambiar GW de la red...
      lineinfile:
        dest: /etc/network/interfaces
        #regexp: '^127\.0\.1\.1[ \t]+debian10temp'
        regexp: 'gateway 10\.45\.0\.99'
        line: '        gateway {{ template_gw }}'
        state: present

