---
- hosts: all
  become: yes
  tasks:
    - name: add myself to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1[ \t]+debian10temp'
        line: '127.0.1.1       {{ template_hosts }}.ansv.gov.ar {{ template_hosts }}'
        state: present
