- name: "Join Domain"
    win_domain_membership:
      dns_domain_name: nprod.gob.ar
      hostname: win2
      domain_admin_user: ansible@nprod.gob.ar
      domain_admin_password: enterpass
      state: domain
    register: domain_state
  - win_reboot:
    when: domain_state.reboot_required
