---
- hosts: all
  become: yes
  vars:
    - inventory_hostname = www.test.com
  tasks:
  - name: Enable server in 'www' backend pool wait until healthy
    community.general.haproxy:
      state: enabled
      host: '{{ inventory_hostname }}'
      backend: www
      wait: yes
