---
- hosts: all
  become: yes
  become_method: sudo 
  tasks:
  - name: Create a 2048-bit SSH key for user ansible in ~ansible/.ssh/id_rsa
    register: output
    ansible.builtin.user:
      name: ansible
      shell: /usr/bin/zsh
      group: sudo
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_type: ed25519
      ssh_key_file: .ssh/id_rsa 

  - name: Set authorized key took from file
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', './files/public_keys/ansible-vm-key.pub') }}"

  - name: Instalar cosas
    apt:
      pkg:
        - zsh

  - ansible.builtin.shell: |
          free -m
    register: output
    ignore_errors: true


  - debug: msg="{{ output }}"
    when: output.rc > 0
  - debug: msg="{% if output.changed == false %} No cambio {% else %} Si cambio {% endif %}" 
  #- debug: msg="prueba texto"
- hosts: apache
  become: yes
  become_method: sudo 
  handlers:
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
  tasks:
  - include_tasks: tasks/Apache/tasks.yml

  - name: Crear directorio para el sitio
    ansible.builtin.file:
      path: /var/www/{{ item.name }}
      state: directory
      mode: '0755' 
    loop: "{{ apache_virtualhosts }}"
    notify: restart apache2

  - name: Create vhost
    ansible.builtin.template:
    #por defecto lo busca en templates...
      src: Apache/vhosts.j2
      dest: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
    loop: "{{ apache_virtualhosts }}"

  - name: Enable service httpd 
    ansible.builtin.systemd:
      name: apache2
      state: started
      enabled: yes

- hosts: haproxy
  become: yes
  become_method: sudo 
  tasks:
  - include_tasks: tasks/HAProxy/tasks.yml

