---
- hosts: all
#  become: yes
#  become_method: sudo
  roles:
#    - apt_upgrade
#    - hostnames
#    - tools
#    - geerlingguy.firewall
#    - geerlingguy.docker
#    - wordpress_docker
    - zshrc
#    - gantsign.oh-my-zsh # este rol falla...
#    - install_oh-my-zsh
#    - apache_docker
#    - haproxy
    - timezone
    - install_antibody
    - role: iancleary.zsh
#      become: yes
#      become_method: sudo
      users:
        - username: ansible
        - username: ansv
      ohmyzsh_bundles:
        - name: zsh-syntax-highlighting
