---
- name: Install sudo
  apt:
    name: sudo

- name: Create "Matias" user
  user:
    name: matias
    shell: /bin/bash
#    uid: 1000
    group: users
    groups: sudo
    append: true # --> user is not removed from any other group
    password: $6$mysecretsalt$y0tDlmIJzhvevRuMmhWZSPh0pO737ziv2qrf/J2H6ZU5MWAjCVMXNg4r5fBgY0iFMGgOKQzxF/6gkBYZniPel.
    #R5QzB&2CJ

