---
-  name: "Create RBAC config"
   hosts: dcs
   tasks:
   - win_shell: install-packageprovider -name nuget -force
   - name: "Install ActiveDirectoryDSC"
     win_psmodule: 
        name: ActiveDirectoryDSC
        state: present
   - name: RBAC config
     ansible.windows.win_dsc:
        resource_name: ADObjectPermissionEntry
        Ensure: Present
        Path: 'OU=servers,DC=domain,DC=local'
        identityReference: 'domain\DB Admins'
        activeDirectoryRights: 'CreateChild,DeleteChild'
        accessControlType: 'Allow'
        objectType: 'bf967a86-0de6-11d0-a285-00aa003049e2'
        activeDirectorySecurityInheritance: 'All'
        inheritedObjectType: '00000000-0000-0000-0000-000000000000'
