---
- hosts: servers
  tasks:
     - name: Update packege lists 
       apt:
        update_cache: yes
     - name: Download PGP security keys
       get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
        force_basic_auth: yes
     - name: Register PGP security keys
       command: 
        cmd: dpkg -i /tmp/packages-microsoft-prod.deb
     - name: Update packege lists
       apt:
        update_cache: yes    
     - name: Install latest version of PowerShell 7
       apt:
        name: powershell
