---
- name: Install sudo
  apt:
    name: sudo

- name: Create "{{ template_usuario }}" user
  user:
    name: {{ template_usuario }}
    shell: /bin/bash
#    uid: 1000
    group: users
    groups: sudo
    append: true # --> user is not removed from any other group
    password: $6$mysecretsalt$y0tDlmIJzhvevRuMmhWZSPh0pO737ziv2qrf/J2H6ZU5MWAjCVMXNg4r5fBgY0iFMGgOKQzxF/6gkBYZniPel.

---
- name: Create "sudo-nopasswd" group
  group:
    name: sudo-nopasswd

- name: Add "sudo-nopasswd" group to "sudoers" file
  lineinfile:
    dest: /etc/sudoers
    line: '%sudo-nopasswd ALL=(ALL:ALL) NOPASSWD:ALL'
    regexp: '^%sudo-nopasswd'


---
- name: Add user "{{ template_usuario }}" to "sudo-nopasswd" group
  user:
    name: {{ template_usuario }}
    groups: sudo-nopasswd
    append: true # --> user is not removed from any other group
  when: passwordless_sudo is defined and passwordless_sudo == true

- name: Remove user "{{ template_usuario }}" from "sudo-nopasswd" group
  shell: /usr/sbin/delgroup matias sudo-nopasswd
  when: not (passwordless_sudo is defined and passwordless_sudo == true)
  ignore_errors: yes
