---
- name: Create "{{ template_usuario }}" user
  user:
    name: {{ template_usuario }}
    shell: /bin/bash
  #  uid: 1000
    group: users
    groups: sudo
    append: true # --> user is not removed from any other group
    password: $6$mysecretsalt$y0tDlmIJzhvevRuMmhWZSPh0pO737ziv2qrf/J2H6ZU5MWAjCVMXNg4r5fBgY0iFMGgOKQzxF/6gkBYZniPel.

- name: Add user "{{ template_usuario }}" to "sudo-nopasswd" group
  user:
    name: {{ template_usuario }}
    groups: sudo-nopasswd
    append: true # --> user is not removed from any other group
  when: passwordless_sudo is defined and passwordless_sudo == true

- name: Remove user "{{ template_usuario }}" from "sudo-nopasswd" group
  shell: /usr/sbin/delgroup {{ template_usuario }} sudo-nopasswd
  when: not (passwordless_sudo is defined and passwordless_sudo == true)
  ignore_errors: yes
