---
- name: "Create matias user's .ssh directory"
  file:
    path: /home/matias/.ssh
    state: directory
    owner: matias
    group: users
    mode: 0700

- name: "Copy matias user's authorized_keys"
  copy:
    src: authorized_keys_matias
    dest: /home/matias/.ssh/authorized_keys
    owner: matias
    group: users
    mode: 0600
