---
- hosts: servers
  tasks:
    - name: Update repository
      apt_repository:
       repo: 'ppa:git-core/ppa'
       state: present
    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes
